// lib/command-center/screenerRankedOpportunitiesState.ts
//
// WA-0005 §15/§16: pure, presentation-independent classification of
// /screener's Ranked Opportunities state-and-staleness contract. Extracted
// from app/screener/page.tsx so this frozen, safety-relevant logic (state 2
// vs. state 5, the Initial/not-yet-run vs. Empty Universe distinction, and
// session-supersession staleness) can be exhaustively unit tested without
// needing to render the full Screener page (which has heavy live
// TastyTrade/IndexedDB/task-manager dependencies unrelated to this
// classification). Presentation-only: does not touch
// lib/opportunity-engine or lib/decision-engine, does not recompute any
// score/confidence/disposition, and is a pure function of its inputs.
//
// PO corrective round, Finding 5: staleness identity corrected. The
// original implementation compared a plain, page-local `useRef` counter
// (`scanRunIdRef`, bumped on every `results` state change, including
// IndexedDB cache-restore on mount -- never a genuine new scan) against
// itself -- an invented identity, not a canonical one. Investigation
// confirmed neither `RecommendationService.generatedAt` (fabricated
// client-side at parse time; the API route never returns a `generatedAt`)
// nor a brand-new producer was needed: `lib/screener/screenerJobStore.ts`'s
// own job `id` (a real per-run identifier, freshly generated by
// `startScreenerJob()` and unchanged until the next scan) already exists,
// and `completeScreenerJob()` already fires, at the exact moment each
// results-affecting scan mode (filter/rank/pmcc/csp, and Ranked Scan via
// `useRankedScan`) sets its real, new results -- confirmed by direct
// grep of every `completeScreenerJob(` call site in app/screener/page.tsx
// and features/screener/hooks/useRankedScan.ts. It is never called for an
// IndexedDB cache-restore. This makes the job store's own `id` the
// existing, canonical, already-available scan/session identity this
// module now consumes, instead of a fabricated counter. Targeted Scan is
// deliberately excluded from the "supersedes" comparison below: it writes
// to `targetedResults`, not `results`, and structurally cannot affect the
// Ranked Opportunities recommendations pipeline -- treating a completed
// Targeted job as "newer" would falsely mark unrelated, still-current
// recommendations stale.

export interface RankedOpportunitiesStateInput {
  opportunityState: 'idle' | 'loading' | 'loaded' | 'error';
  resultsLength: number;
  rawAnalysesLength: number;
  recommendationsLength: number;
  /** The canonical screenerJobStore job id the currently-held recommendations were generated for, or null if none have ever resolved (e.g. an IndexedDB cache-restore, which has no associated job). */
  recommendationsJobId: string | null;
  /** The screenerJobStore job id of the most recently completed, results-affecting scan (filter/rank/pmcc/csp) -- null if no such job has completed this session, or if the most recent completed job was Targeted Scan (which never affects `results`/recommendations). */
  latestResultsAffectingJobId: string | null;
}

export interface RankedOpportunitiesStateResult {
  /** CES §15 state 2: rawAnalyses existed but none became OpportunityRecommendations. */
  isState2: boolean;
  /** CES §15 state 5: scan results existed, but the evaluation service produced zero analyses at all. */
  isState5: boolean;
  /** CES §16: the currently-displayed recommendations predate the most recently completed scan. */
  isStale: boolean;
}

export function classifyRankedOpportunitiesState(input: RankedOpportunitiesStateInput): RankedOpportunitiesStateResult {
  const isState2 =
    input.opportunityState === 'loaded' && input.rawAnalysesLength > 0 && input.recommendationsLength === 0;
  const isState5 =
    input.opportunityState === 'loaded' &&
    input.resultsLength > 0 &&
    input.rawAnalysesLength === 0 &&
    input.recommendationsLength === 0;
  // Deliberately does NOT require `recommendationsJobId !== null`: a
  // currently-displayed set with no job basis at all (e.g. generated from
  // an IndexedDB cache-restore, which has no associated scan job) is just
  // as genuinely superseded once a real, results-affecting job completes
  // as one generated by an earlier job would be. The `recommendationsLength
  // > 0` guard below already covers "nothing to show yet" -- a separate
  // null-guard on recommendationsJobId would incorrectly make a
  // cache-restored presentation permanently immune to staleness.
  const isStale =
    input.latestResultsAffectingJobId !== null &&
    input.recommendationsJobId !== input.latestResultsAffectingJobId &&
    input.recommendationsLength > 0;

  return { isState2, isState5, isStale };
}

export type EmptyUniverseClassification = 'not-yet-run' | 'empty-universe' | 'has-results';

/**
 * CES §11/§15: distinguishes "no scan has ever run this session" (Initial/
 * not-yet-run) from "a scan completed and found zero raw candidates" (state
 * 1, Empty Universe) -- both otherwise look identical via resultsLength ===
 * 0 alone. Neither is ever worded as "no qualifying opportunities."
 */
export function classifyEmptyUniverseState(input: {
  resultsLength: number;
  scanHasRunThisSession: boolean;
}): EmptyUniverseClassification {
  if (input.resultsLength > 0) return 'has-results';
  return input.scanHasRunThisSession ? 'empty-universe' : 'not-yet-run';
}
