/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './pages/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './app/**/*.{js,ts,jsx,tsx,mdx}',
    // TE-0007D corrective — features/** was missing from this list entirely.
    // Every class used only inside features/ (31 files, including the
    // PMCC/CC/CSP scan modals) was never scanned or generated by Tailwind,
    // in any build, since the directory was first created -- not a
    // regression introduced by any recent change. This is the actual root
    // cause of the white-on-white input bug reported in the scan modals;
    // last night's [color-scheme:dark] fix on ScanModalShell addressed a
    // plausible but incorrect theory and never touched the real cause.
    './features/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: { extend: {} },
  plugins: [],
};
