// lib/discovery/qv/reasons.ts

// LEAPS-QV-0001 Gate 3 (Section 45.12) -- the QV-v1.0 reason-code registry.
//
// Reason codes are STRUCTURED evidence: the classifiers build them from the same comparisons that decide a state, and
// the explanation text is derived from the reason object itself (explainReasons), so a decision and its explanation
// cannot drift apart.
//
// Grammar deviation (reported): Gate 1's reason-code grammar requires a leading category (QUALITY / VALUATION /
// FUNDAMENTAL / TECHNICAL / RISK / DATA / LEAPS / LIFECYCLE). Three Section 45.12 names have no category prefix, so
// they are emitted with one; QV_SPEC_REASON_CONCEPTS maps every Section 45.12 name to the code actually emitted.

import { createReason, explainReasons } from '../reasonCodes';
import type { ReasonCode, ReasonEvidence } from '../reasonCodes';
import type { NormalizedMetric } from '../metrics';
import type { JsonObject } from '../util';
import { deepFreeze } from '../util';

export const FUNDAMENTAL_DIMENSIONS = ['REVENUE', 'EPS', 'OPERATING_MARGIN', 'FCF', 'LEVERAGE'] as const;
export type FundamentalDimension = (typeof FUNDAMENTAL_DIMENSIONS)[number];

export const TRAJECTORIES = ['DETERIORATING', 'STABLE', 'IMPROVING'] as const;
export type Trajectory = (typeof TRAJECTORIES)[number];

const dimensionCodes: string[] = [];
FUNDAMENTAL_DIMENSIONS.forEach((dimension) => {
  TRAJECTORIES.forEach((trajectory) => dimensionCodes.push(`FUNDAMENTAL_${dimension}_${trajectory}`));
});

export const QV_REASON = deepFreeze({
  // Quality
  QUALITY_REVENUE_STRONG: 'QUALITY_REVENUE_STRONG',
  QUALITY_REVENUE_ACCEPTABLE: 'QUALITY_REVENUE_ACCEPTABLE',
  QUALITY_REVENUE_WEAK: 'QUALITY_REVENUE_WEAK',
  QUALITY_OPERATING_MARGIN_POSITIVE: 'QUALITY_OPERATING_MARGIN_POSITIVE',
  QUALITY_OPERATING_MARGIN_NON_POSITIVE: 'QUALITY_OPERATING_MARGIN_NON_POSITIVE',
  QUALITY_FCF_POSITIVE: 'QUALITY_FCF_POSITIVE',
  QUALITY_FCF_NEGATIVE_TEMPORARY: 'QUALITY_FCF_NEGATIVE_TEMPORARY',
  QUALITY_FCF_NEGATIVE_PERSISTENT: 'QUALITY_FCF_NEGATIVE_PERSISTENT',
  QUALITY_FCF_DETERIORATING: 'QUALITY_FCF_DETERIORATING',
  QUALITY_ROIC_STRONG: 'QUALITY_ROIC_STRONG',
  QUALITY_ROIC_ACCEPTABLE: 'QUALITY_ROIC_ACCEPTABLE',
  QUALITY_ROIC_WEAK: 'QUALITY_ROIC_WEAK',
  QUALITY_LEVERAGE_STRONG: 'QUALITY_LEVERAGE_STRONG',
  QUALITY_LEVERAGE_ACCEPTABLE: 'QUALITY_LEVERAGE_ACCEPTABLE',
  QUALITY_LEVERAGE_ELEVATED: 'QUALITY_LEVERAGE_ELEVATED',
  QUALITY_LEVERAGE_HIGH: 'QUALITY_LEVERAGE_HIGH',
  QUALITY_PASS: 'QUALITY_PASS',
  QUALITY_FAIL_OPERATING_MARGIN: 'QUALITY_FAIL_OPERATING_MARGIN',
  QUALITY_FAIL_LEVERAGE_WITH_WEAKNESS: 'QUALITY_FAIL_LEVERAGE_WITH_WEAKNESS',
  QUALITY_FAIL_MULTIPLE_WEAKNESSES: 'QUALITY_FAIL_MULTIPLE_WEAKNESSES',
  // Valuation
  VALUATION_DISLOCATION_STRONG: 'VALUATION_DISLOCATION_STRONG',
  VALUATION_DISLOCATION_MODERATE: 'VALUATION_DISLOCATION_MODERATE',
  VALUATION_NO_MATERIAL_DISLOCATION: 'VALUATION_NO_MATERIAL_DISLOCATION',
  VALUATION_CONFLICT: 'VALUATION_CONFLICT',
  VALUATION_WINDOW_3Y_FALLBACK: 'VALUATION_WINDOW_3Y_FALLBACK',
  VALUATION_GROWTH_ADJUSTED_INTACT: 'VALUATION_GROWTH_ADJUSTED_INTACT',
  VALUATION_GROWTH_ADJUSTED_MIXED: 'VALUATION_GROWTH_ADJUSTED_MIXED',
  VALUATION_GROWTH_ADJUSTED_DETERIORATING: 'VALUATION_GROWTH_ADJUSTED_DETERIORATING',
  // Fundamentals
  FUNDAMENTAL_MOMENTUM_IMPROVING: 'FUNDAMENTAL_MOMENTUM_IMPROVING',
  FUNDAMENTAL_MOMENTUM_STABILIZING: 'FUNDAMENTAL_MOMENTUM_STABILIZING',
  FUNDAMENTAL_MOMENTUM_DETERIORATING: 'FUNDAMENTAL_MOMENTUM_DETERIORATING',
  FUNDAMENTAL_INTEGRITY_INTACT: 'FUNDAMENTAL_INTEGRITY_INTACT',
  FUNDAMENTAL_THESIS_BROKEN: 'FUNDAMENTAL_THESIS_BROKEN',
  // Technical
  TECHNICAL_DECLINING: 'TECHNICAL_DECLINING',
  TECHNICAL_OVERSOLD: 'TECHNICAL_OVERSOLD',
  TECHNICAL_STABILIZING: 'TECHNICAL_STABILIZING',
  TECHNICAL_RECOVERING: 'TECHNICAL_RECOVERING',
  // Risk
  RISK_EARNINGS_APPROACHING: 'RISK_EARNINGS_APPROACHING',
  RISK_BINARY_EVENT_PENDING: 'RISK_BINARY_EVENT_PENDING',
  RISK_LEVERAGE_ELEVATED: 'RISK_LEVERAGE_ELEVATED',
  RISK_LEVERAGE_HIGH: 'RISK_LEVERAGE_HIGH',
  RISK_VALUATION_CONFLICT: 'RISK_VALUATION_CONFLICT',
  RISK_FUNDAMENTAL_DETERIORATION: 'RISK_FUNDAMENTAL_DETERIORATION',
  // Data
  DATA_ANALYST_REVISION_DATA_UNAVAILABLE: 'DATA_ANALYST_REVISION_DATA_UNAVAILABLE',
  DATA_REQUIRED_DATA_UNAVAILABLE: 'DATA_REQUIRED_DATA_UNAVAILABLE',
  DATA_LEVERAGE_TRAJECTORY_UNAVAILABLE: 'DATA_LEVERAGE_TRAJECTORY_UNAVAILABLE',
  // Lifecycle / classification
  LIFECYCLE_STATE_DISCOVERED: 'LIFECYCLE_STATE_DISCOVERED',
  LIFECYCLE_STATE_WATCH: 'LIFECYCLE_STATE_WATCH',
  LIFECYCLE_STATE_SETUP: 'LIFECYCLE_STATE_SETUP',
  LIFECYCLE_STATE_ACTIONABLE: 'LIFECYCLE_STATE_ACTIONABLE',
  LIFECYCLE_STATE_INVALIDATED: 'LIFECYCLE_STATE_INVALIDATED',
  LIFECYCLE_UNMET_QUALITY: 'LIFECYCLE_UNMET_QUALITY',
  LIFECYCLE_UNMET_VALUATION: 'LIFECYCLE_UNMET_VALUATION',
  LIFECYCLE_UNMET_GROWTH_ADJUSTED: 'LIFECYCLE_UNMET_GROWTH_ADJUSTED',
  LIFECYCLE_UNMET_MOMENTUM: 'LIFECYCLE_UNMET_MOMENTUM',
  LIFECYCLE_UNMET_TECHNICAL: 'LIFECYCLE_UNMET_TECHNICAL',
  LIFECYCLE_UNMET_RISK: 'LIFECYCLE_UNMET_RISK',
  LIFECYCLE_THESIS_BREAK_NO_PRIOR_THESIS: 'LIFECYCLE_THESIS_BREAK_NO_PRIOR_THESIS',
} as const);

/** Per-dimension trajectory codes, e.g. FUNDAMENTAL_REVENUE_DETERIORATING (generated once, from the two enumerations above). */
export const QV_DIMENSION_REASON_CODES: readonly string[] = deepFreeze(dimensionCodes);

export type QvReasonCode = (typeof QV_REASON)[keyof typeof QV_REASON];

/** Every code the QV-v1.0 strategy can emit (explicit list + generated dimension codes). */
export const QV_ALL_REASON_CODES: readonly string[] = deepFreeze([
  ...Object.keys(QV_REASON).map((key) => (QV_REASON as Record<string, string>)[key]),
  ...dimensionCodes,
]);

export function dimensionReasonCode(dimension: FundamentalDimension, trajectory: Trajectory): string {
  return `FUNDAMENTAL_${dimension}_${trajectory}`;
}

/** Section 45.12 name -> the code the strategy emits. Names that already satisfy the Gate 1 grammar map to themselves. */
export const QV_SPEC_REASON_CONCEPTS: Readonly<Record<string, string>> = deepFreeze({
  QUALITY_REVENUE_STRONG: QV_REASON.QUALITY_REVENUE_STRONG,
  QUALITY_REVENUE_ACCEPTABLE: QV_REASON.QUALITY_REVENUE_ACCEPTABLE,
  QUALITY_REVENUE_WEAK: QV_REASON.QUALITY_REVENUE_WEAK,
  QUALITY_FCF_POSITIVE: QV_REASON.QUALITY_FCF_POSITIVE,
  QUALITY_FCF_DETERIORATING: QV_REASON.QUALITY_FCF_DETERIORATING,
  QUALITY_ROIC_STRONG: QV_REASON.QUALITY_ROIC_STRONG,
  QUALITY_ROIC_ACCEPTABLE: QV_REASON.QUALITY_ROIC_ACCEPTABLE,
  QUALITY_ROIC_WEAK: QV_REASON.QUALITY_ROIC_WEAK,
  QUALITY_LEVERAGE_STRONG: QV_REASON.QUALITY_LEVERAGE_STRONG,
  QUALITY_LEVERAGE_ACCEPTABLE: QV_REASON.QUALITY_LEVERAGE_ACCEPTABLE,
  QUALITY_LEVERAGE_ELEVATED: QV_REASON.QUALITY_LEVERAGE_ELEVATED,
  QUALITY_LEVERAGE_HIGH: QV_REASON.QUALITY_LEVERAGE_HIGH,
  VALUATION_DISLOCATION_STRONG: QV_REASON.VALUATION_DISLOCATION_STRONG,
  VALUATION_DISLOCATION_MODERATE: QV_REASON.VALUATION_DISLOCATION_MODERATE,
  VALUATION_NO_MATERIAL_DISLOCATION: QV_REASON.VALUATION_NO_MATERIAL_DISLOCATION,
  VALUATION_CONFLICT: QV_REASON.VALUATION_CONFLICT,
  GROWTH_ADJUSTED_INTACT: QV_REASON.VALUATION_GROWTH_ADJUSTED_INTACT,
  GROWTH_ADJUSTED_MIXED: QV_REASON.VALUATION_GROWTH_ADJUSTED_MIXED,
  GROWTH_ADJUSTED_DETERIORATING: QV_REASON.VALUATION_GROWTH_ADJUSTED_DETERIORATING,
  FUNDAMENTAL_MOMENTUM_IMPROVING: QV_REASON.FUNDAMENTAL_MOMENTUM_IMPROVING,
  FUNDAMENTAL_MOMENTUM_STABILIZING: QV_REASON.FUNDAMENTAL_MOMENTUM_STABILIZING,
  FUNDAMENTAL_MOMENTUM_DETERIORATING: QV_REASON.FUNDAMENTAL_MOMENTUM_DETERIORATING,
  FUNDAMENTAL_THESIS_BROKEN: QV_REASON.FUNDAMENTAL_THESIS_BROKEN,
  TECHNICAL_DECLINING: QV_REASON.TECHNICAL_DECLINING,
  TECHNICAL_OVERSOLD: QV_REASON.TECHNICAL_OVERSOLD,
  TECHNICAL_STABILIZING: QV_REASON.TECHNICAL_STABILIZING,
  TECHNICAL_RECOVERING: QV_REASON.TECHNICAL_RECOVERING,
  ANALYST_REVISION_DATA_UNAVAILABLE: QV_REASON.DATA_ANALYST_REVISION_DATA_UNAVAILABLE,
  RISK_EARNINGS_APPROACHING: QV_REASON.RISK_EARNINGS_APPROACHING,
  REQUIRED_DATA_UNAVAILABLE: QV_REASON.DATA_REQUIRED_DATA_UNAVAILABLE,
});

export type QvEvidence = NormalizedMetric | ReasonEvidence;

/** The one constructor the classifiers use, so every QV reason is a registered code. */
export function qvReason(
  code: string,
  polarity: ReasonCode['polarity'],
  evidence: readonly QvEvidence[] = [],
  params?: JsonObject,
): ReasonCode {
  if (QV_ALL_REASON_CODES.indexOf(code) < 0) throw new Error(`"${code}" is not a registered QV-v1.0 reason code.`);
  return createReason({ code, polarity, evidence, ...(params ? { params } : {}) });
}

/** Explanation text derived from the structured reasons (same objects the decision used). */
export function explainQvReasons(reasons: readonly ReasonCode[]): string[] {
  return explainReasons(reasons);
}
